name: Execution of Cypress Cucumber Boilerplate Scenarios
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'     
        required: true
        default: 'chrome'
      spec:
        description: 'Specs (sub)folder or file to be included in the execution'
        required: true
        default: 'features/saphetor.feature'
      tags:
        description: 'Tags to be included'
        required: true
        default: 'not @exercise'
  # schedule:
    # - cron:  '0 1 * * 1-5' # Runs every day on 1:00AM UTC (4:00AM Athens) only on Weekdays
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checking out the git branch
     uses: actions/checkout@v3
     with:
      repository: gpepignosis/cypress_cucumber_boilerplate
      ref: main
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: Setup Node.js environment
     uses: actions/setup-node@v3
     with:
       node-version: '18'

   - name: Install Node Packages
     run: npm install

   - name: Execute scenarios
     run: npx cypress run --browser "${{ github.event.inputs.browser }}" --spec "${{ github.event.inputs.spec }}" -e TAGS="${{ github.event.inputs.tags }}" --headless

   - name: Generate the report
     run: node cucumber-html-report.js

  # Save the HTML reports folder as an artifact for future inspection
   - name: Save reports folder
     uses: actions/upload-artifact@v3
     with:
       name: reports
       if-no-files-found: error
       path: reports/html
